spring.profiles.active=dev
spring.application.name=attract-service-${spring.profiles.active}
server.port=28016
server.servlet.context-path=/
# nacos
spring.cloud.nacos.discovery.enabled=false
# jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.jackson.serialization.write-dates-as-timestamps=false

# ????
feign.httpclient.enabled=false
# ????
feign.okhttp.enabled=true
# ????
feign.hystrix.enabled=false
# default context ??????
feign.client.config.default.connectTimeout = 5000
# default context ?????
feign.client.config.default.readTimeout = 10000