
spring.jmx.enabled=false
java.security.egd=file:/dev/./urandom


spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.mvc.date-format=yyyy-MM-dd HH:mm:ss

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
server.servlet.session.timeout=2200000

security.test=false
#security.test=true

ws.client.url=ws://localhost:8631/wsChat/client/api
