# nacos
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.main.allow-bean-definition-overriding=true

logging.level.org.apache.http=info
logging.level.root=info
logging.path=/home/logs/dev/hotel/hotel-daemon
logging.config=classpath:logback-spring.xml