spring.profiles.active=dev
spring.application.name=hotel-daemon-${spring.profiles.active}
server.port=28015
server.servlet.context-path=/
# nacos
spring.cloud.nacos.discovery.enabled=true
# jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.jackson.serialization.write-dates-as-timestamps=false
#spring.jackson.default-property-inclusion=non_null

# ??Hystrix??
# ????
feign.httpclient.enabled=false
# ????
feign.okhttp.enabled=true
# ????
feign.hystrix.enabled=false
# ????
feign.sentinel.enabled=true

# default context ??????
feign.client.config.default.connectTimeout = 5000
# default context ?????
feign.client.config.default.readTimeout = 10000

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds= 30000

# ??????????1??????FeignClient??connectTimeout??
ribbon.ConnectTimeout=5000
# ?????????1??????FeignClient??readTimeout??
ribbon.ReadTimeout=10000
# ??????
ribbon.MaxAutoRetries=1
