#==============db-setting=====================
#db.url=jdbc:mysql://<DATABASE_HOST>/<DATABASE>?<PARAMS>
#db.username=root
#db.password=<REDACTED>
db.url=jdbc:mysql://rm-8vbb9iojjwm7tex407o.mysql.zhangbei.rds.aliyuncs.com:3306/security_login?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&verifyServerCertificate=false&useSSL=false
db.username=stroot
db.password=<REDACTED>
db.driverClassName=com.mysql.cj.jdbc.Driver


entity.package.path=com.zzy.security.lib.entity
entity.project.path=D:/BproSpace/codeSpace/idea-sp/jzg-realm-system/security-login/src/main/java
dao.package.path=com.zzy.security.lib.dao
dao.project.path=D:/BproSpace/codeSpace/idea-sp/jzg-realm-system/security-login/src/main/java
xml.mapper.path=D:/BproSpace/codeSpace/idea-sp/jzg-realm-system/security-login/src/main/resources