#==============db-setting=====================
#db.url=jdbc:mysql://<DATABASE_HOST>/<DATABASE>?<PARAMS>
#db.username=root
#db.password=<REDACTED>
db.url=jdbc:mysql://rm-8vbb9iojjwm7tex407o.mysql.zhangbei.rds.aliyuncs.com:3306/jzg_realm_system?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&verifyServerCertificate=false&useSSL=false
db.username=stroot
db.password=<REDACTED>
db.driverClassName=com.mysql.cj.jdbc.Driver
table.name=complain_event_info

parent.package.path=com.zzy

entity.package.path=db.entity.eventdepart
dao.package.path=db.dao.eventdepart
xml.path=mapper/eventdepart

service.package.path=api.service.eventdepart
serviceImpl.package.path=api.service.eventdepart.impl

controller.package.path=api.controller

controller.project.path=jzg-realm-api
service.project.path=jzg-realm-api
dao.project.path=jzg-realm-db
