# nacos
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.main.allow-bean-definition-overriding=true

#spring.jackson.default-property-inclusion=non_null
# mysql
#spring.datasource.druid.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.driver-class-name=com.p6spy.engine.spy.P6SpyDriver
#spring.datasource.druid.url=jdbc:p6spy:mysql://<DATABASE_HOST>/<DATABASE>?<PARAMS>
spring.datasource.druid.url=jdbc:p6spy:mysql://<DATABASE_HOST>/b2c_ticket_supplier?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
#spring.datasource.druid.username=root
spring.datasource.druid.username=zzysaas
#spring.datasource.druid.password=<REDACTED>
spring.datasource.druid.password=<REDACTED>
spring.datasource.druid.initial-size=5
spring.datasource.druid.min-idle=5
spring.datasource.druid.maxActive=20
spring.datasource.druid.maxWait=1000
spring.datasource.druid.timeBetweenEvictionRunsMillis=60000
spring.datasource.druid.minEvictableIdleTimeMillis=300000
spring.datasource.druid.validationQuery=SELECT 1 FROM DUAL
spring.datasource.druid.testWhileIdle=true
spring.datasource.druid.testOnBorrow=false
spring.datasource.druid.testOnReturn=false
spring.datasource.druid.poolPreparedStatements=true
spring.datasource.druid.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.druid.filters=stat,slf4j
spring.datasource.druid.connectionProperties=druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
spring.datasource.druid.web-stat-filter.enabled=true
spring.datasource.druid.web-stat-filter.url-pattern=/*
spring.datasource.druid.web-stat-filter.exclusions=*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*.

spring.datasource.druid.stat-view-servlet.url-pattern=/druid/*
spring.datasource.druid.stat-view-servlet.allow=127.0.0.1
spring.datasource.druid.stat-view-servlet.deny=
spring.datasource.druid.stat-view-servlet.reset-enable=false
spring.datasource.druid.stat-view-servlet.login-username=admin
spring.datasource.druid.stat-view-servlet.login-password=<REDACTED>
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-swallow-size=100MB

logging.level.org.apache.http=info
logging.level.root=info
logging.path=/home/logs/dev/ticket/ticket-service
logging.config=classpath:logback-spring.xml

spring.redis.database=0
spring.redis.host=<PUBLIC_HOST>
spring.redis.port=6379
spring.redis.password=<REDACTED>
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-wait=-1
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=0

spring.redis.redisson.singleServerConfig.address=redis://<PUBLIC_HOST>:6379
spring.redis.redisson.singleServerConfig.thread=4

spring.redis.redisson.singleServerConfig.codec=org.redisson.codec.JsonJacksonCodec
spring.redis.redisson.singleServerConfig.connectionMinimumIdleSize=5
spring.redis.redisson.singleServerConfig.idleConnectionTimeout=5000
spring.redis.redisson.singleServerConfig.pingTimeout=1000
spring.redis.redisson.singleServerConfig.connectTimeout=10000
spring.redis.redisson.singleServerConfig.timeout=3000
spring.redis.redisson.singleServerConfig.retryAttempts=2
spring.redis.redisson.singleServerConfig.retryInterval=1500
spring.redis.redisson.singleServerConfig.reconnectionTimeout=3000
spring.redis.redisson.singleServerConfig.failedAttempts=2
spring.redis.redisson.singleServerConfig.password=<REDACTED>
spring.redis.redisson.singleServerConfig.subscriptionsPerConnection=5

spring.redis.redisson.singleServerConfig.subscriptionConnectionMinimumIdleSize=1
spring.redis.redisson.singleServerConfig.subscriptionConnectionPoolSize=10
spring.redis.redisson.singleServerConfig.connectionPoolSize=10
spring.redis.redisson.singleServerConfig.database=5
spring.redis.redisson.singleServerConfig.dnsMonitoring=false
spring.redis.redisson.singleServerConfig.dnsMonitoringInterval=5000

douyin.refund.notify.url = http://8.142.91.21:9013/douyin/refundSuccessNotify
douyin.settle.notify.url = http://8.142.91.21:9013/douyin/settleNotify
gateway.refund.notify.url = http://8.142.91.21:9013/gateway/refundSuccessNotify