#spring.datasource.secondary.url=jdbc:mysql://<DATABASE_HOST>/<DATABASE>?<PARAMS>
#spring.datasource.secondary.username=root
#spring.datasource.secondary.password=<REDACTED>
spring.datasource.secondary.url=jdbc:mysql://rm-8vbb9iojjwm7tex407o.mysql.zhangbei.rds.aliyuncs.com:3306/security_login?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&verifyServerCertificate=false&useSSL=false
spring.datasource.secondary.username=stroot
spring.datasource.secondary.password=<REDACTED>
spring.datasource.secondary.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.secondary.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.secondary.name=dataSource2
spring.datasource.secondary.filters=stat,wall
spring.datasource.secondary.initialSize=5
spring.datasource.secondary.minIdle=3
spring.datasource.secondary.maxActive=20
spring.datasource.secondary.maxWait=60000
spring.datasource.secondary.timeBetweenEvictionRunsMillis=60000
spring.datasource.secondary.minEvictableIdleTimeMillis=50000
spring.datasource.secondary.validationQuery=SELECT 'x'
spring.datasource.secondary.testWhileIdle=true
spring.datasource.secondary.testOnBorrow=false
spring.datasource.secondary.testOnReturn=false
spring.datasource.secondary.defaultAutoCommit=true
spring.datasource.secondary.poolPreparedStatements=false
spring.datasource.secondary.maxPoolPreparedStatementPerConnectionSize=-1
spring.datasource.secondary.useGlobalDataSourceStat=true
spring.datasource.secondary.removeAbandoned=true
spring.datasource.secondary.removeAbandonedTimeout=60

