spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.main.allow-bean-definition-overriding=true

#spring.jackson.default-property-inclusion=non_null
# mysql
#spring.datasource.druid.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.driver-class-name=com.p6spy.engine.spy.P6SpyDriver
#spring.datasource.druid.url=jdbc:p6spy:mysql://<DATABASE_HOST>/<DATABASE>?<PARAMS>
spring.datasource.druid.url=jdbc:p6spy:mysql://<DATABASE_HOST>/saas_v1?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
#spring.datasource.druid.username=root
spring.datasource.druid.username=zzysaas
#spring.datasource.druid.password=<REDACTED>
spring.datasource.druid.password=<REDACTED>
spring.datasource.druid.initial-size=5
spring.datasource.druid.min-idle=5
spring.datasource.druid.maxActive=20
spring.datasource.druid.maxWait=1000
spring.datasource.druid.timeBetweenEvictionRunsMillis=60000
spring.datasource.druid.minEvictableIdleTimeMillis=300000
spring.datasource.druid.validationQuery=SELECT 1 FROM DUAL
spring.datasource.druid.testWhileIdle=true
spring.datasource.druid.testOnBorrow=false
spring.datasource.druid.testOnReturn=false
spring.datasource.druid.poolPreparedStatements=true
spring.datasource.druid.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.druid.filters=stat,slf4j
spring.datasource.druid.connectionProperties=druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
spring.datasource.druid.web-stat-filter.enabled=true
spring.datasource.druid.web-stat-filter.url-pattern=/*
spring.datasource.druid.web-stat-filter.exclusions=*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*.

spring.datasource.druid.stat-view-servlet.url-pattern=/druid/*
spring.datasource.druid.stat-view-servlet.allow=127.0.0.1
spring.datasource.druid.stat-view-servlet.deny=
spring.datasource.druid.stat-view-servlet.reset-enable=false
spring.datasource.druid.stat-view-servlet.login-username=admin
spring.datasource.druid.stat-view-servlet.login-password=<REDACTED>
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-swallow-size=200MB

minio.endPoint=http://<PUBLIC_HOST>:8184
minio.accessKey=<REDACTED>
minio.secretAccessKey=<REDACTED>
minio.bucketName=thor
oss.file.domain=https://data.ctpaas.com/oss

logging.level.org.apache.http=info
logging.level.root=info
logging.path=/home/logs/nuwa/zeus-api
logging.config=classpath:logback-spring.xml


# Redis���ݿ�������Ĭ��Ϊ0��
spring.redis.database=0
# Redis��������ַ
spring.redis.host=8.142.91.21
# Redis���������Ӷ˿�
spring.redis.port=6379
# Redis�������������루Ĭ��Ϊ�գ�
spring.redis.password=<REDACTED>
# ���ӳ������������ʹ�ø�ֵ��ʾû�����ƣ� Ĭ�� 8
spring.redis.lettuce.pool.max-active=8
# ���ӳ���������ȴ�ʱ�䣨ʹ�ø�ֵ��ʾû�����ƣ� Ĭ�� -1
spring.redis.lettuce.pool.max-wait=-1
# ���ӳ��е����������� Ĭ�� 8
spring.redis.lettuce.pool.max-idle=8
# ���ӳ��е���С�������� Ĭ�� 0
spring.redis.lettuce.pool.min-idle=0

app.url.appId.fixed=9001,20211012,20211041
app.url.appId.inflexible=20211022
app.url.wechat.miniapp=https://mch-v2.zhongzhiyou.cn/#/renovation/index
app.url.alibaba.miniapp=https://mch-v2.zhongzhiyou.cn/#/renovation/index
app.url.wechat.official=https://mch-v2.zhongzhiyou.cn/#/renovation/index

upYun.endPoint=https://file.zhongzhiyou.cn
upYun.operatorName=saas
upYun.operatorPwd=LCLllmVpS8fr1lHhRyhJXGWNp0hqX6rJ
upYun.bucketName=saas-bucket
upYun.domain=https://file.zhongzhiyou.cn