spring.profiles.active=dev
spring.application.name=ticket-user-api-${spring.profiles.active}
server.port=28017
server.servlet.context-path=/
# nacos
spring.cloud.nacos.discovery.enabled=true
# jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.jackson.serialization.write-dates-as-timestamps=false
#spring.jackson.default-property-inclusion=non_null
