meituanJzgHotelTask=0 01 04 * * ?
meituanJzgScenicTask=0 38 05 * * ?
meituanJzgRestaurantTask=0 18 06 * * ?
meituanJzgScenicTagTask=0 05 19 * * ?
xiechengJzgScenicTask=0 05 04 * * ?
xiechengJzgRestaurantTask=0 39 05 * * ?
tongchengJzgScenicTask=0 11 05 * * ?
tongchengJzgHotelTask=0 13 06 * * ?
tuNiuJzgScenicTask=0 02 06 * * ?
tuNiuJzgHotelTask=0 15 07 * * ?
lvmmJzgScenicTask=0 41 07 * * ?
lvmmJzgHotelTask=0 33 08 * * ?
quNarJzgScenicTask=0 03 03 * * ?


