meituanJzgHotelTask=0 01 02 * * ?
meituanJzgScenicTask=0 38 02 * * ?
meituanJzgRestaurantTask=0 18 03 * * ?
meituanJzgScenicTagTask=0 05 19 * * ?
xiechengJzgScenicTask=0 05 02 * * ?
xiechengJzgRestaurantTask=0 49 02 * * ?
tongchengJzgScenicTask=0 11 01 * * ?
tongchengJzgHotelTask=0 13 02 * * ?
tuNiuJzgScenicTask=0 02 01 * * ?
tuNiuJzgHotelTask=0 15 02 * * ?
lvmmJzgScenicTask=0 41 02 * * ?
lvmmJzgHotelTask=0 33 03 * * ?
quNarJzgScenicTask=0 03 02 * * ?


